"""add review fields to time_off requests

Revision ID: 46e38e9d84d5
Revises: 46efba371ed8
Create Date: 2026-05-19 12:27:33.249691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46e38e9d84d5'
down_revision = '46efba371ed8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('admin_note', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_leave_requests_reviewer_id'), ['reviewer_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['reviewer_id'], ['id'])

    with op.batch_alter_table('overtime_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('admin_note', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_overtime_requests_reviewer_id'), ['reviewer_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['reviewer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('overtime_requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_overtime_requests_reviewer_id'))
        batch_op.drop_column('admin_note')
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('reviewer_id')

    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_leave_requests_reviewer_id'))
        batch_op.drop_column('admin_note')
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('reviewer_id')

    # ### end Alembic commands ###
