"""add time_off models

Revision ID: 46efba371ed8
Revises: 
Create Date: 2026-05-19 12:22:42.148362

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '46efba371ed8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leave_requests_employee_id'), ['employee_id'], unique=False)

    op.create_table('overtime_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hours', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('overtime_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_overtime_requests_employee_id'), ['employee_id'], unique=False)

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_column('check_out_lunch')
        batch_op.drop_column('check_in_morning')
        batch_op.drop_column('check_in_afternoon')
        batch_op.drop_column('check_out_evening')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_out_evening', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('check_in_afternoon', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('check_in_morning', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('check_out_lunch', mysql.DATETIME(), nullable=True))

    with op.batch_alter_table('overtime_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_overtime_requests_employee_id'))

    op.drop_table('overtime_requests')
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leave_requests_employee_id'))

    op.drop_table('leave_requests')
    # ### end Alembic commands ###
